backend:
  name: git-gateway
  repo: ljbraun/laurel-ronning-portfolio
  branch: main

media_folder: "static/images"
public_folder: "/static/images"

collections:
  - name: "portfolio"
    label: "Portfolio "
    label_singular: "Portfolio Item"
    folder: "content/portfolio"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "portfolio/{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      # - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: "Summary", name: "summary", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "images", widget: "image", required: false }
      # - {
      #     label: "Featured Image",
      #     name: "featuredImage",
      #     widget: "image",
      #     required: false,
      #     allow_multiple: false,
      #   }
  - name: "sections"
    label: "Sections "
    label_singular: "Section"
    folder: "content/sections"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "section/{{title}}/index"
    editor:
      preview: false
    fields:
      - { label: "Project Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "markdown" }
      - { label: "Full description", name: "body", widget: "markdown" }
      # - {
      #     label: "Featured Image",
      #     name: "featuredImage",
      #     widget: "image",
      #     required: false,
      #     allow_multiple: false,
      #   }
      - { label: "Link", name: "link", widget: "string", required: false }
      - {
          label: "Featured Image",
          name: "images",
          widget: "image",
          required: true,
        }
